---
- name: Load distro-specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install epel-release
  package: name=epel-release
  when: ansible_os_family == "RedHat"

- name: Install base packages
  package:
    name:
      - curl
      - htop
      - ntp
      - tmux
      - vim
      - wget

- include_tasks: sshd.yml
  tags: sshd
- include_tasks: ntp.yml
  tags: ntp
