---
- name: Load distro-specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- include: "{{ ansible_distribution }}.yml"

- name: Install base packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - ntp
    - wget
    - git
    - vim
    - tmux
    - zsh

- name: configure screen
  lineinfile:
    state: present
    dest: /etc/screenrc
    regexp: startup_message
    line: startup_message off

- include: sshd.yml
  tags: sshd
- include: ntp.yml
  tags: ntp
- include: swap.yml
  tags: swap
- include: firewall.yml
  tags: firewall
- include: user.yml
  tags: user
