---
- name: Load distro-specific vars
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- name: Install epel-release
  package: name=epel-release
  when: ansible_os_family == "RedHat"
  tags: pkg

- include_tasks: user.yml
  tags: user
- include_tasks: sshd.yml
  tags: sshd
- include_tasks: ntp.yml
  tags: ntp
