---
- name: Set Timezone to Europe/Zurich
  timezone:
    name: Europe/Zurich

- name: Install NTP
  package:
    name: ntp
    state: present

- name: Enable NTP
  service:
    name: "{{ ntp_service_name }}"
    enabled: yes
    state: started
