---
- name: Configure swappiness
  sysctl:
    name: vm.swappiness
    value: 1
    state: present
    reload: true

- name: Create the swapfile
  command: fallocate -l 4G /swapfile
  args:
    creates: /swapfile
  register: swapfile_created

- name: Set proper /swapfile permissions
  file:
    path: /swapfile
    state: file
    owner: root
    group: root
    mode: "0600"
  when: not ansible_check_mode

- name: Initialize swapfile
  command: mkswap /swapfile
  when: swapfile_created | changed

- name: Enable swap
  command: swapon /swapfile
  when: swapfile_created | changed

- name: Add swap to fstab
  mount:
    src: /swapfile
    name: none
    fstype: swap
    opts: sw,nofail
    state: present
