---
- user:
    name: "{{ username }}"
    group: "{{ username }}"
    shell: /bin/zsh
    state: present
  register: managed_user

- authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ pubkey_url }}"

- name: add user to sudoers
  template:
    src: templates/sudoers.j2
    dest: /etc/sudoers.d/{{ username }}
    owner: root
    group: root
    mode: '0440'
    validate: visudo -cf %s

- name: install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ managed_user.home }}/.oh-my-zsh"
    accept_hostkey: yes

- name: fix permissions
  file:
    path: "{{ managed_user.home }}/.oh-my-zsh"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: true
